### ISSUE TITLE
Variables defined in RenderStatePackager resource layout but not in the shaders cause run-time crashes

### ISSUE THREAD

**Issue by speedym** [DiligentGraphics/DiligentTools#101]
Diligent is asserting / crashing when unpacking a PSO which has a variable set in the .json resource layout which is not present in the shaders:

Diligent Engine: ERROR in ValidatePipelineResourceSignatures() (PipelineStateBase.cpp, 363): Description of graphics PSO 'xxx.vert+xxxx.frag' is invalid: Resource layout contains variable 'InstancedTransforms' that is not present in the implicit resource signatre. Note that PSO_CREATE_FLAG_IMPLICIT_SIGNATURE0 flag is for internal use only. If you see this message while unpacking PSO from the archive, this might indicate a bug.
Diligent Engine: ERROR in CreateDeviceObject() (RenderDeviceBase.hpp, 511): Failed to create Pipeline State object 'xxxx.vert+xxxx.frag'

**Comment by speedym** [comment]
Looking further into this issue, it got triggered by the following upgrade on our side:

   GIT_REPOSITORY https://github.com/DiligentGraphics/DiligentCore.git
-  GIT_TAG        15bd593ad0cbdb735b9f5b597dafda784b3b654c
+  GIT_TAG        6c519efeb933c9ce5a4d1b404c76f7bfef1ec1e6

      GIT_REPOSITORY git@github.com:znly/DiligentCorePro.git
-     GIT_TAG        3e07310b6e3dac6be4c04ee9d454c52034f934ce
+     GIT_TAG        b7bcff78efa23b0671ad4d34868b196dbce01a3f

   GIT_REPOSITORY https://github.com/DiligentGraphics/DiligentTools.git
-  GIT_TAG        f76a7520ce083963d848316107acac1eab4dffc8
+  GIT_TAG        f32158c73955aac5db1b1a8cec821fedaf34555d

With original versions, it works fine.

**Comment by TheMostDiligent** [comment]
This new validation may be overly aggressive - will take a look.

**Comment by speedym** [comment]
Yup, just tested and can confirm this bug is resolved. Thanks!
