### ISSUE TITLE
UseCombinedTextureSamplers not working on Metal but working fine on Vulkan

### ISSUE THREAD

**Issue by speedym** [DiligentGraphics/DiligentTools#102]
It seems that during PSO shader compilation using RenderStatePackager on iOS / Metal, UseCombinedTextureSamplers is ignored, while it works fine on Linux / Vulkan.

The errors I'm getting on the iOS platform are the following:

Diligent Engine: ERROR: Unable to bind resource to shader variable 'xxxx_sampler': resource is not found in the resource mapping. Do not use BIND_SHADER_RESOURCES_VERIFY_ALL_RESOLVED flag to suppress the message if this is not an issue.

Diligent Engine: ERROR: No resource is assigned to static shader variable 'xxxx_sampler' in pipeline resource signature 'Implicit signature of PSO 'xxxx.vert+xxxx.frag''.

Diligent Engine: ERROR: No resource is bound to variable 'xxxx_sampler' in shader '0x10A816778' of PSO 'xxxx.vert+xxxx.frag'

validateFunctionArguments:3838: failed assertion `Fragment Function(main0): missing sampler binding at index 0 for xxxx_sampler[0].  

We are including texture samplers with the shader resource view SetSampler() function.

**Comment by TheMostDiligent** [comment]
The issue should be fixed in the latest version now.
@speedym Can you test and update the issue?

**Comment by speedym** [comment]
Fixed, thank you!
