### ISSUE TITLE
DiligentTools configure step python pip errors

### ISSUE THREAD

**Issue by speedym** [DiligentGraphics/DiligentTools#110]
After upgrading to latest DiligentTools, I'm getting the following configure step errors:

Using build configuration file 
custom_configure_build() function not found in 
Target Platform: iOS
Neither VULKAN_SDK nor MOLTENVK_LIBRARY is defined. Vulkan backend will be disabled.
D3D11_SUPPORTED:  FALSE
D3D12_SUPPORTED:  FALSE
GL_SUPPORTED:     FALSE
GLES_SUPPORTED:   FALSE
VULKAN_SUPPORTED: FALSE
METAL_SUPPORTED:  TRUE
-- SPIRV-Cross: Finding Git version for SPIRV-Cross.
-- Found Git: /usr/bin/git (found version "2.32.0 (Apple Git-132)") 
-- SPIRV-Cross: Git hash: 1d871d31
-- Found PythonInterp: /usr/bin/python (found version "2.7.16") 
Requirement already satisfied: libclang in /Library/Python/2.7/site-packages (12.0.0)
You are using pip version 18.1, however version 20.3.4 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
Collecting jinja2
  Downloading https://files.pythonhosted.org/packages/7e/c2/1eece8c95ddbc9b1aeb64f5783a9e07a286de42191b7204d67b7496ddf35/Jinja2-2.11.3-py2.py3-none-any.whl (125kB)
Collecting MarkupSafe>=0.23 (from jinja2)
  Downloading https://files.pythonhosted.org/packages/6d/d2/0ccd2c0e2cd93b35e765d9b3205cd6602e6b202b522fc7997531353715b3/MarkupSafe-1.1.1-cp27-cp27m-macosx_10_6_intel.whl
Installing collected packages: MarkupSafe, jinja2
Could not install packages due to an EnvironmentError: [Errno 13] Permission denied: '/Library/Python/2.7/site-packages/markupsafe'
Consider using the `--user` option or check the permissions.

You are using pip version 18.1, however version 20.3.4 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
CMake Error at 3rdparty/DiligentTools/RenderStateNotationParser/CMakeLists.txt:35 (message):
  python -m pip install jinja2 failed with 1

-- Configuring incomplete, errors occurred!

Installing those dependencies manually with sudo fixes the build issues:

$ sudo python -m pip install jinja2

I haven't had those problems before upgrading.

**Comment by TheMostDiligent** [comment]
For some reason it did not find Python 3...
Did you try to clean the CMake cache / do clean build?

**Comment by speedym** [comment]
When using brew to manage software on my Mac, there is a python which comes with the system in /usr/bin/python and the python3 from brew in /usr/local/bin/python3. It seems CMake is finding and using the default one.

% python --version
Python 2.7.16
% brew info python
python@3.9: stable 3.9.9 (bottled)
Interpreted, interactive, object-oriented programming language
https://www.python.org/
/usr/local/Cellar/python@3.9/3.9.9 (3,084 files, 55MB) *
  Poured from bottle on 2022-01-13 at 22:19:18
From: https://github.com/Homebrew/homebrew-core/blob/HEAD/Formula/python@3.9.rb
License: Python-2.0
==> Dependencies
Build: pkg-config ✘
Required: gdbm ✔, mpdecimal ✔, openssl@1.1 ✔, readline ✔, sqlite ✔, xz ✔
==> Caveats
Python has been installed as
  /usr/local/bin/python3

Unversioned symlinks `python`, `python-config`, `pip` etc. pointing to
`python3`, `python3-config`, `pip3` etc., respectively, have been installed into
  /usr/local/opt/python@3.9/libexec/bin

You can install Python packages with
  pip3 install <package>
They will install into the site-package directory
  /usr/local/lib/python3.9/site-packages

tkinter is no longer included with this formula, but it is available separately:
  brew install python-tk@3.9

See: https://docs.brew.sh/Homebrew-and-Python
==> Analytics
install: 417,532 (30 days), 2,057,804 (90 days), 8,107,893 (365 days)
install-on-request: 215,528 (30 days), 942,197 (90 days), 3,097,988 (365 days)
build-error: 240 (30 days)

**Comment by TheMostDiligent** [comment]
Yes, we found a bug in the CMake, we will fix it.

**Comment by speedym** [comment]
I have upgraded to the latest Diligent and now I've have the following error on my Mac, iOS build:

Using build configuration file 
custom_configure_build() function not found in 
Target Platform: iOS
Neither VULKAN_SDK nor MOLTENVK_LIBRARY is defined. Vulkan backend will be disabled.
D3D11_SUPPORTED:  FALSE
D3D12_SUPPORTED:  FALSE
GL_SUPPORTED:     FALSE
GLES_SUPPORTED:   FALSE
VULKAN_SUPPORTED: FALSE
METAL_SUPPORTED:  TRUE
-- SPIRV-Cross: Finding Git version for SPIRV-Cross.
-- Found Git: /usr/bin/git (found version "2.32.0 (Apple Git-132)") 
-- SPIRV-Cross: Git hash: 1d871d31
-- Found PythonInterp: /usr/bin/python (found version "2.7.16") 
CMake Error at /usr/local/Cellar/cmake/3.22.1/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
  Could NOT find PythonInterp: Found unsuitable version "2.7.16", but
  required is at least "3" (found /usr/bin/python)
Call Stack (most recent call first):
  /usr/local/Cellar/cmake/3.22.1/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:592 (_FPHSA_FAILURE_MESSAGE)
  /usr/local/Cellar/cmake/3.22.1/share/cmake/Modules/FindPythonInterp.cmake:169 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
  3rdparty/DiligentTools/RenderStateNotation/CMakeLists.txt:24 (find_package)

Here are a few tests I did:

% python3
Python 3.9.9 (main, Nov 21 2021, 03:23:42) 
[Clang 13.0.0 (clang-1300.0.29.3)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> exit()

% python --version
Python 2.7.16
% python2

WARNING: Python 2.7 is not recommended. 
This version is included in macOS for compatibility with legacy software. 
Future versions of macOS will not include Python 2.7. 
Instead, it is recommended that you transition to using 'python3' from within Terminal.

Python 2.7.16 (default, Sep  6 2021, 07:39:44) 
[GCC Apple LLVM 12.0.5 (clang-1205.0.19.59.6) [+internal-os, ptrauth-isa=deploy on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> exit()
%

The following CMake code fixes the issue on my end:

find_package(Python3 REQUIRED)
if(NOT Python3_FOUND)
    message(FATAL_ERROR "Python3 package not found.")
endif()
if(NOT Python3_Interpreter_FOUND)
    message(FATAL_ERROR "Python3 interpreter not found.")
endif()

execute_process(COMMAND ${Python3_EXECUTABLE} -m pip install libclang
                RESULT_VARIABLE PYTHON_PIP_LIBCLANG_RESULT)
if(NOT PYTHON_PIP_LIBCLANG_RESULT EQUAL "0")
    message(FATAL_ERROR "${Python3_EXECUTABLE} -m pip install libclang failed with ${PYTHON_PIP_LIBCLANG_RESULT}")
endif()

execute_process(COMMAND ${Python3_EXECUTABLE} -m pip install jinja2
                RESULT_VARIABLE PYTHON_PIP_JINJIA_RESULT)
if(NOT PYTHON_PIP_JINJIA_RESULT EQUAL "0")
    message(FATAL_ERROR "${Python3_EXECUTABLE} -m pip install jinja2 failed with ${PYTHON_PIP_JINJIA_RESULT}")
endif()

execute_process(COMMAND ${Python3_EXECUTABLE} "${CMAKE_CURRENT_SOURCE_DIR}/scripts/cxx_generator.py" --dir "${RSN_PARSER_GENERATED_HEADERS_DIR}" --files ${REFLECTED}
                RESULT_VARIABLE PYTHON_GENERATOR_RESULT)
if(NOT PYTHON_PIP_LIBCLANG_RESULT EQUAL "0")
    message(FATAL_ERROR "${Python3_EXECUTABLE} ${CMAKE_CURRENT_SOURCE_DIR}/scripts/cxx_generator.py failed with ${PYTHON_GENERATOR_RESULT}")
endif()

**Comment by speedym** [comment]
I have also found I have python 3.8.9 in /usr/bin/python3 (probably comes with OS X).

Homebrew installed python 3.9.9 in /usr/local/Cellar/python@3.9/3.9.9/bin/python3 which is a symbolic link to:

lrwxr-xr-x   1 xxxxxx  admin   55 Nov 15 19:05 python3 -> ../Frameworks/Python.framework/Versions/3.9/bin/python3

It's pretty odd that FindPythonInterp can't find any of those two python3 interpreters. I think this is likely a CMake bug. Which CMake version are you using and which OS X version do you have? 

Also, have you managed to reproduce the issue on your end? I would suggest removing CMake & python3 if you have them installed separately, then installing CMake & python3 via homebrew, and then try building Diligent.

I have a theory regarding why find_package(Python3 REQUIRED) is failing on Windows. It could be that it's looking for a python3 executable and there is no python3 executable available on the Windows PC / CI?

**Comment by speedym** [comment]
Ah, I think I've found the culprit - looking at the source code of FindPythonInterp, it says it's deprecated and that we should use FindPython3:

FindPythonInterp
----------------

.. deprecated:: 3.12

  Use :module:`FindPython3`, :module:`FindPython2` or :module:`FindPython` instead.

It seems to me that the right way to go is to try to fix your Windows build and use FindPython3 as per my code.

**Comment by speedym** [comment]
Here are a few links regarding similar Windows CMake issues - they might be of help:

https://gitlab.kitware.com/cmake/cmake/-/issues/19024
https://stackoverflow.com/questions/55021986/cmake-findpython3-failing-to-find-interpreter-on-windows

It would be great if you could try out the following in your Windows build:
find_package(Python3 REQUIRED Interpreter)
(notice the Interpreter at the end)

According to the quick reading of the above links it seems find_package(Python3 ...) has problems when trying to match development libs / headers & interpreter on Windows. 

If the above does not work, maybe a fallback solution could be to use FindPython3 for all arches except Windows where you can use FindPythonInterp. Not super clean, but it should at least work across the board.

**Comment by speedym** [comment]
Additional info: FindPythonInterp fails to find Python 3 on Linux / Ubuntu / QT Creator with the same error.

@MikhailGorobets: Just curious and looking at the above code changes, have you checked if find_package(Python3 REQUIRED COMPONENTS Interpreter) works on Windows?

**Comment by TheMostDiligent** [comment]
Fixed in https://github.com/DiligentGraphics/DiligentCore/commit/59dc95f09b1ee9442cb109b5fa6b2cd611bc7ce8
