### ISSUE TITLE
RenderStatePackager: Add option to dump optimised SPIRV so that we can analyse it

### ISSUE THREAD

**Issue by speedym** [DiligentGraphics/DiligentTools#117]
We are using some shader analysis tools which are operating over optimised SPIRV, so it would be great if RenderStatePackager could output the optimised SPIRV code based on provided options.

**Comment by TheMostDiligent** [comment]
Use `-d`/`--dump_dir` [command line argument](https://github.com/DiligentGraphics/DiligentTools/tree/master/RenderStatePackager#command-line-arguments) to specify the dump folder.
