### ISSUE TITLE
Odd random RenderStatePackager build errors

### ISSUE THREAD

**Issue by speedym** [DiligentGraphics/DiligentTools#119]
After updating to latest the following error appears randomly in the XCode log without actually causing errors in builds or runtime (ie. tool is returning success 0 as an exit code). I didn't observe any problems in run-time, but I didn't test in great detail so far.

In some runs the error appears, in some it doesn't (I would estimate around 50%/50% is the chance to reproduce it).

With the following commits I haven't observed this error (I would have to double-check it to be 100% sure as the bug is random):
DiligentCore       
4ee66b631168df5a379f044fe17fe87e8a05cc67
DiligentCorePro 
e99c420a7bc07c0267967d20f48cc58e66547bad
DiligentTools 
2f91d3aea6fc9743b011a6c2f26fa5bfe66ed21b

This bug very much reminds of this issue:
https://github.com/DiligentGraphics/DiligentTools/issues/100

Error log:
Showing Recent Messages
Unable to parse built-ins

ERROR: 0:1: '' : array size must be a positive integer

ERROR: 0:1: '' : compilation terminated 

INTERNAL ERROR: Unable to parse built-ins

const mediump int  gl_MaxVertexAttribs = 64;const mediump int  gl_MaxVertexUniformVectors = 128;const mediump int  gl_MaxVertexTextureImageUnits = 32;const mediump int  gl_MaxCombinedTextureImageUnits = 80;const mediump int  gl_MaxTextureImageUnits = 32;const mediump int  gl_MaxFragmentUniformVectors = 16;const mediump int  gl_MaxDrawBuffers = 32;const mediump int  gl_MaxVertexOutputVectors = 16;const mediump int  gl_MaxFragmentInputVectors = 15;const mediump int  gl_MinProgramTexelOffset = -8;const mediump int  gl_MaxProgramTexelOffset = 7;const int gl_MaxGeometryInputComponents = 64;const int gl_MaxGeometryOutputComponents = 128;const int gl_MaxGeometryImageUniforms = 0;const int gl_MaxGeometryTextureImageUnits = 16;const int gl_MaxGeometryOutputVertices = 256;const int gl_MaxGeometryTotalOutputComponents = 1024;const int gl_MaxGeometryUniformComponents = 1024;const int gl_MaxGeometryAtomicCounters = 0;const int gl_MaxGeometryAtomicCounterBuffers = 0;const int gl_MaxTessControlInputComponents = 128;const int gl_MaxTessControlOutputComponents = 128;const int gl_MaxTessControlTextureImageUnits = 16;const int gl_MaxTessControlUniformComponents = 1024;const int gl_MaxTessControlTotalOutputComponents = 4096;const int gl_MaxTessEvaluationInputComponents = 128;const int gl_MaxTessEvaluationOutputComponents = 128;const int gl_MaxTessEvaluationTextureImageUnits = 16;const int gl_MaxTessEvaluationUniformComponents = 1024;const int gl_MaxTessPatchComponents = 120;const int gl_MaxPatchVertices = 32;const int gl_MaxTessGenLevel = 64;const int gl_MaxTessControlImageUniforms = 0;const int gl_MaxTessEvaluationImageUniforms = 0;const int gl_MaxTessControlAtomicCounters = 0;const int gl_MaxTessEvaluationAtomicCounters = 0;const int gl_MaxTessControlAtomicCounterBuffers = 0;const int gl_MaxTessEvaluationAtomicCounterBuffers = 0;const mediump int gl_MaxDualSourceDrawBuffersEXT = 0;mediump vec4 gl_SecondaryFragColorEXT;mediump vec4 gl_SecondaryFragDataEXT[gl_MaxDualSourceDrawBuffersEXT];

const ivec3 gl_MaxComputeWorkGroupCount = ivec3(65535,65535,65535);const ivec3 gl_MaxComputeWorkGroupSize = ivec3(1024,1024,64);const int gl_MaxComputeUniformComponents = 1024;const int gl_MaxComputeTextureImageUnits = 16;

const int gl_MaxImageUnits = 8;const int gl_MaxCombinedShaderOutputResources = 8;const int gl_MaxVertexImageUniforms = 0;const int gl_MaxFragmentImageUniforms = 8;const int gl_MaxCombinedImageUniforms = 8;const int gl_MaxComputeImageUniforms = 8;const int gl_MaxComputeAtomicCounters = 8;const int gl_MaxComputeAtomicCounterBuffers = 1;

const int gl_MaxVertexAtomicCounters = 0;const int gl_MaxFragmentAtomicCounters = 8;const int gl_MaxCombinedAtomicCounters = 8;const int gl_MaxAtomicCounterBindings = 1;const int gl_MaxVertexAtomicCounterBuffers = 0;const int gl_MaxFragmentAtomicCounterBuffers = 1;const int gl_MaxCombinedAtomicCounterBuffers = 1;const int gl_MaxAtomicCounterBufferSize = 16384;const int gl_MaxSamples = 4;const int gl_MaxMeshOutputVerticesNV = 256;const int gl_MaxMeshOutputPrimitivesNV = 512;const ivec3 gl_MaxMeshWorkGroupSizeNV = ivec3(32,1,1);const ivec3 gl_MaxTaskWorkGroupSizeNV = ivec3(32,1,1);const int gl_MaxMeshViewCountNV = 4;

**Comment by TheMostDiligent** [comment]
Can you provide a bit more context regarding this issue.
We don't even know how to try to approach it.

**Comment by speedym** [comment]
I think the best approach is to first fix #100 and then let me know, so I can retest this one. I have a feeling fixing #100 will fix this one as well.
