### ISSUE TITLE
RenderStatePackeger hits MAX_PATH limit on the Windows platform

### ISSUE THREAD

**Issue by speedym** [DiligentGraphics/DiligentTools#127]
RenderStatePackeger is hitting MAX_PATH limitation on Windows when opening .json files which are deep in subfolder hierarchy.

**Comment by TheMostDiligent** [comment]
This issue should be fixed in the latest version of core module - please try updating it and check if it works now.

**Comment by MikhailGorobets** [comment]
It works now.
