### ISSUE TITLE
Hitting recently introduced compilation error

### ISSUE THREAD

**Issue by Gaspard--** [DiligentGraphics/DiligentTools#130]
I updated diligent tools in my submodules recently and hit a new error that I didn't have before.
- Linux, g++ (GCC) 11.2.1 20210728 (Red Hat 11.2.1-1). Apparenlty not officially supported but ha been working for us for a while.
- Using cmake 3.20.5
- DiligentCore, DiligentFx and DiligentTools are all at the head of the master branch
The error:
```DiligentTools/RenderStatePackager/src/main.cpp:30:10: fatal error: args.hxx: No such file or directory```

There seems to be no such file in the repo (`find` returns nothing) so it's hard to know how to troubleshoot the issue on my end.
I don't use _RenderStatePackager_ in my projects however so this isn't blocking, it just means the cmake always fails on this project.

I hope this issue is helpful.

**Comment by TheMostDiligent** [comment]
You need to update submodules - the missing file is in the new submodule that has been added recently
