### ISSUE TITLE
DiligentTools fails to compile on Mac M1 & latest Android Studio

### ISSUE THREAD

**Issue by speedym** [DiligentGraphics/DiligentTools#150]
DiligentTools fails to compile with the following Android Studio version:

Android Studio Bumblebee | 2021.1.1 Patch 1
Build #AI-211.7628.21.2111.8139111, built on February 1, 2022
Runtime version: 11.0.11+0-b60-7772763 aarch64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 12.1
GC: G1 Young Generation, G1 Old Generation
Memory: 3072M
Cores: 10
Registry: external.system.auto.import.disabled=true
Non-Bundled Plugins: org.jetbrains.kotlin (211-1.6.10-release-923-AS7442.40), org.intellij.plugins.markdown (211.7142.37)

but compiles fine with:

Android Studio Arctic Fox | 2020.3.1
Build #AI-203.7717.56.2031.7583922, built on July 26, 2021
Runtime version: 11.0.10+0-b96-7281165 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 12.1
GC: G1 Young Generation, G1 Old Generation
Memory: 3072M
Cores: 10
Registry: external.system.auto.import.disabled=true

The error message is:

clang.cindex.LibclangError: dlopen(/Users/xxxx/Library/Python/3.8/lib/python/site-packages/clang/native/libclang.dylib, 0x0006): tried: '/Users/xxxx/Library/Python/3.8/lib/python/site-packages/clang/native/libclang.dylib' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64e')), '/usr/local/lib/libclang.dylib' (no such file), '/usr/lib/libclang.dylib' (no such file). To provide a path to libclang use Config.set_library_path() or Config.set_library_file().

Notice that the previous Android Studio version is arch x86_64 but the latest one is aarch64.

**Comment by TheMostDiligent** [comment]
Fixed in https://github.com/MikhailGorobets/DiligentTools/commit/e354b33256b63e72bba2a3adc77d1bc51cf7f3c5

**Comment by speedym** [comment]
Just to confirm that this one is fixed.
