### ISSUE TITLE
RenderStatePackager memory related random crash on MacOS

### ISSUE THREAD

**Issue by speedym** [DiligentGraphics/DiligentTools#154]
After upgrading to latest, RenderStatePackager started randomly producing SIGSEGV on MacOS due to double free of a object.

% ./start.sh 
Diligent Engine: Info: Purged 0 deleted objects from the sampler registry

% ./start.sh
Diligent Engine: Info: Purged 0 deleted objects from the sampler registry

% ./start.sh
Diligent-RenderStatePackager_mac(40656,0x70000c308000) malloc: Double free of object 0x7fb7dea04140
./start.sh: line 2: 40656 Segmentation fault: 11  ./Diligent-RenderStatePackager_mac --metal_ios -o xxxx.bin -i xxxx1.json -i xxxx2.json -i xxxx3.json

I'm sending a repro case via email.

**Comment by TheMostDiligent** [comment]
Should be fixed in https://github.com/DiligentGraphics/DiligentCore/commit/497153feff118f090a55e6ce712c1b324160aab7
Please feel free to reopen the issue if the problem happens again.
