### ISSUE TITLE
Relative path breaks compile

### ISSUE THREAD

**Issue by hamyyy** [DiligentGraphics/DiligentTools#158]
These two lines of code:

https://github.com/DiligentGraphics/DiligentTools/blob/f8d74fff4d786ab3207080b601545f53056a527d/Imgui/interface/ImGuiUtils.hpp#L33-L34

should be replaced with:
```
#include "imgui.h"
#include "imgui_internal.h"
```
because it ignores `DILIGENT_DEAR_IMGUI_PATH` cmake variable

**Comment by TheMostDiligent** [comment]
Fixed in https://github.com/DiligentGraphics/DiligentTools/commit/6788ef87d806b1af243f3b35ec57de8044e1491f
