### ISSUE TITLE
Render state packager: add tests for shader creation errors

### ISSUE THREAD

**Issue by TheMostDiligent** [DiligentGraphics/DiligentTools#164]
Add tests that verify that RenderStatePackager properly handles shader creation failures:
- Add test for missing shader source
- Add test for invalid shader source that compiles with error

**Comment by MikhailGorobets** [comment]
These tests should be in `DiligentCore` for `SerializationDeviceImpl::CreateShader`. 
The packager only checks if the pointer is valid
```
pDevice->CreateShader(..., ..., &pShader);
if (!pShader)
{
   ....
}
```

**Comment by TheMostDiligent** [comment]
Yes, [I added tests for these case in the core](https://github.com/DiligentGraphics/DiligentCore/blob/master/Tests/DiligentCoreAPITest/src/ArchiveTest.cpp#L371-L461).
It is important however that packager does not crash when there are issues with the shaders and handle this properly.

**Comment by MikhailGorobets** [comment]
We have the https://github.com/DiligentGraphics/DiligentTools/blob/69a9dddf3c135e11a1c8818896ea79ea3fc80f76/Tests/DiligentToolsTest/src/RenderStatePackager/RenderStatePackagerTest.cpp#L137 test for a such case
