### ISSUE TITLE
Add tests for HLSL2GLSLConverterApp

### ISSUE THREAD

**Issue by TheMostDiligent** [DiligentGraphics/DiligentTools#181]

**Comment by AndreyMlashkin** [comment]
What do you think about moving HLSL2GLSLConverterApp to a separate repository?
It does not have any dependencies in diligent tools, it only depends on Diligent-Core.

I have tried it locally and it was super easy to move it to Diligent-Engine level. I can commit my changes, if you are for it.

**Comment by TheMostDiligent** [comment]
What is the reason?

**Comment by AndreyMlashkin** [comment]
One repository - one responsibility.
Actually, in our complany, we only need HLSL2GLSLConverterApp and don't need the rest of diligent-tools for our purposes.
It would save some CI time. Maybe we are not alone and other users would also have a benifit out of it.

**Comment by TheMostDiligent** [comment]
HLSL2GLSLConverterApp is a very small project. Moving it to a separate repository will create more burden than add a value. Splitting components at too fine granularity creates a lot of overhead.

> Actually, in our complany, we only need HLSL2GLSLConverterApp and don't need the rest of diligent-tools for our purposes.
It would save some CI time.

You can remove all targets you don't need from the build by setting the `EXCLUDE_FROM_ALL` and `EXCLUDE_FROM_DEFAULT_BUILD` properties:
```CMaje
set_target_properties(Diligent-AssetLoader Diligent-Imgui PROPERTIES EXCLUDE_FROM_ALL 1 EXCLUDE_FROM_DEFAULT_BUILD 1)
```
