### ISSUE TITLE
Add option to redirect diligent error messages

### ISSUE THREAD

**Issue by mctb32** [DiligentGraphics/DiligentTools#2]
It would be great if I could redirect the log messages generated by Diligent, so that we could integrate it with our logging system. A simple callback would suffice.

Also, errors in shaders shouldn't display a blocking message box on Win32. Again, a callback or return value with error description would be better.

**Comment by DiligentGraphics** [comment]
Moved the issue to main repository https://github.com/DiligentGraphics/DiligentEngine/issues/9
