### ISSUE TITLE
GLTF Material not matched

### ISSUE THREAD

**Issue by widefire** [DiligentGraphics/DiligentTools#232]
The GLTF material not matched with some files.while the gltf file materials not empty,but some primitive material_id == -1,these primitives used the last of materials. 
I found in founction [void Model::LoadMaterials(const tinygltf::Model& gltf_model, const ModelCreateInfo::MaterialLoadCallbackType& MaterialLoadCallback)](https://github.com/DiligentGraphics/DiligentTools/blob/fe2bc14c747314a6924fc59c6782a4697b5c6473/AssetLoader/src/GLTFLoader.cpp#L1330) create default material only when the gltf file no materials:

    if (Materials.empty())
    {
        // Push a default material for meshes with no material assigned
        Materials.push_back(Material{});
    }

in function https://github.com/DiligentGraphics/DiligentTools/blob/fe2bc14c747314a6924fc59c6782a4697b5c6473/AssetLoader/interface/GLTFBuilder.hpp#L356
        NewMesh.Primitives.emplace_back(
            IndexStart,
            IndexCount,
            VertexCount,
            GltfPrimitive.GetMaterialId() >= 0 ? static_cast<Uint32>(GltfPrimitive.GetMaterialId()) : static_cast<Uint32>(m_Model.Materials.size() - 1),
            PosMin,
            PosMax //
        );
just use the last material while Primitive mateiral_id < 0, so these primitives display error

**Comment by TheMostDiligent** [comment]
Can you provide a model that reproduces this problem?

**Comment by widefire** [comment]
this is a gltf file display error in GLTF Viewer
[basic_sample_new_material.zip](https://github.com/user-attachments/files/16517010/basic_sample_new_material.zip)
trees and car colored red,as below
![gltf_viewer](https://github.com/user-attachments/assets/08c85b68-7139-4744-988c-d7f3a69ad0c7)
but they are no materials,in three.js like this:
![three](https://github.com/user-attachments/assets/7a6ffe39-c61b-4dcf-b2ca-236bbaf5e1ac)
