### ISSUE TITLE
Create Texture from memory or from stream

### ISSUE THREAD

**Issue by mctb32** [DiligentGraphics/DiligentTools#3]
It would be great if the texture loader component contained functions to create textures not only from files, but also from memory or from user streams. It seems the functionality is almost there, but it's not exposed to the end user. Also the image types are deduced from file extensions, rather than from the actual file headers.

**Comment by DiligentGraphics** [comment]
This functionality is in fact already there. If you want to create a image from memory, you can use
`Image::CreateFromDataBlob()` function that also allows you to specify the image format. A texture can then be created from this image with `CreateTextureFromImage()` function. If you have a DDS data blob, you can create a texture from it with `CreateTextureFromDDS()`.
