### ISSUE TITLE
RenderStatePackager: add option to output dependency file for shaders

### ISSUE THREAD

**Issue by TheMostDiligent** [DiligentGraphics/DiligentTools#54]
glslang should have an option to output dependency file for includes after unrolling all macros. If it is the case, we should add an option to RenderStatePackager to output dependency files for all shaders in the json file.
The tool should take a shader depenency directory as command line option and write dependency files in this directory.

**Comment by speedym** [comment]
@TheMostDiligent, I might provided some bad info here, glslc has for sure the output dependency option. I think glslang does not have it (last time I checked). Maybe it might be worth rechecking on your end.
