### ISSUE TITLE
Replace libjepg with libjpeg-turbo submodule

### ISSUE THREAD

**Issue by DiligentGraphics** [DiligentGraphics/DiligentTools#6]
https://github.com/libjpeg-turbo/libjpeg-turbo

**Comment by TheMostDiligent** [comment]
Note that libjpeg-turbo [does not not support sub-project builds](https://github.com/libjpeg-turbo/libjpeg-turbo/blob/main/BUILDING.md#sub-project-builds), which may be a dealbreaker
