### ISSUE TITLE
RenderStatePackager: blend state is not packaged properly

### ISSUE THREAD

**Issue by TheMostDiligent** [DiligentGraphics/DiligentTools#87]
Blend state may not be parsed / packaged by the render state packager.
![bug_report](https://user-images.githubusercontent.com/61806567/147288685-889b8748-85e0-42d4-99db-683f3fd84f43.png)

**Comment by MikhailGorobets** [comment]
I sent an example to Milan.  This solved the problem

**Comment by TheMostDiligent** [comment]
Please make sure that the error message clearly explains the issue.
