### ISSUE TITLE
RenderStatePackager is not using multiple threads on MacOS

### ISSUE THREAD

**Issue by speedym** [DiligentGraphics/DiligentTools#88]
CPU usage of RenderStatePackager is around 10% with 90% of the CPU being idle when compiling multiple .json files on MacOS (--metal_ios).

**Comment by MikhailGorobets** [comment]
What is stage of execution? Shader compilation or archive serialization?
Also try experimenting with the number of threads (argument `-t`)

**Comment by speedym** [comment]
@MikhailGorobets I have sent a repro case via email as it is under NDA. I think only one instance of the metal tool is called at any given moment.

**Comment by speedym** [comment]
I have just retested with the latest RenderStatePackager and I can confirm that this issue has not been fixed. The idle% when using top command line tool is 90%, and the average CPU usage is around 10%.

**Comment by TheMostDiligent** [comment]
The packager starts the specified number of threads, and on MacOS it starts individual process to compile shaders in every thread. Our initial investigation showed that there is a bottleneck in GLSLang memory allocator.
We will investigate this issue further.

**Comment by TheMostDiligent** [comment]
Apparently, this works OK on M1 MacBooks, so there might be some issue on Apple side.
@speedym closing this now, but feel free to reopen if the issue is still relevant.
