### ISSUE TITLE
export IPHONEOS_DEPLOYMENT_TARGET=11 breaks RenderStatePackager

### ISSUE THREAD

**Issue by speedym** [DiligentGraphics/DiligentTools#97]
If you set environment variable IPHONEOS_DEPLOYMENT_TARGET to 11 by using:

export IPHONEOS_DEPLOYMENT_TARGET=11

and then run RenderStatePackager, the compilation process always fails with:

metal: warning: using sysroot for 'MacOSX' but targeting 'iPhone' [-Wincompatible-sysroot]
LLVM ERROR: Error opening '/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/metal/macos/bin/../lib/clang/31001.363/lib/darwin/libmetal_rt_ios.a': No such file or directory!
Diligent Engine: ERROR in PatchShaderMtl() (Archiver_Mtl.mm, 485): Failed to read shader library

Diligent Engine: ERROR: Failed to compile Metal shaders

Diligent Engine: ERROR in Execute() (RenderStatePackager.cpp, 224): Failed to archive graphics pipeline 'xxxx.vert+xxxx.frag'.

Diligent Engine: CRITICAL ERROR in main() (main.cpp, 151): Failed to archive
  
This is a problem for us as we have to build for the deployment target 11 and XCode sets this variable as part of the environment for executing custom defined scripts (ie. shader building).

Removing the deployment target environment variable with:

unset IPHONEOS_DEPLOYMENT_TARGET

fixed the problem, but likely compiles the shaders for the wrong deployment target.

**Comment by speedym** [comment]
Looking into this a bit more, I can confirm that the PSO compilation works after adding unset IPHONEOS_DEPLOYMENT_TARGET in front of the RenderStatePackager invocation, but then I'm getting the following error in the run-time: 

Diligent Engine: ERROR in PipelineStateMtlImpl() (PipelineStateMtlImpl.mm, 505): Failed to create Metal render pipeline for PSO 'xxxx.vert+xxxx.frag': Error Domain=AGXMetalA13 Code=3 "Function main0 is using language version 2.4 which is incompatible with this OS." UserInfo={NSLocalizedDescription=Function main0 is using language version 2.4 which is incompatible with this OS.}

Diligent Engine: ERROR in CreateDeviceObject() (RenderDeviceBase.hpp, 511): Failed to create Pipeline State object 'xxxx.vert+xxxx.frag'

**Comment by TheMostDiligent** [comment]
@speedym It appears that unsetting the variable before running the packager is the only and correct way to fix this.
The run-time problem seems to be not related to the original issue - apparently the Metal Shading language version is incompatible with the device.

**Comment by TheMostDiligent** [comment]
I think it should be possible to set the language version through the command line options that are provided to the packager during the initialization.

**Comment by TheMostDiligent** [comment]
With this change DiligentGraphics/DiligentCore@0b826c8 the packager will only compile shaders for MacOS and/or iOS when the corresponding option is specified.
Can you try this and close the issue if you think it solves the problem?

**Comment by speedym** [comment]
Yup, the issue has been fixed.
