### ISSUE TITLE
File2Include tool is not built outside of the source tree

### ISSUE THREAD

**Issue by speedym** [DiligentGraphics/DiligentTools#98]
It seems Diligent is not building File2String in the binary output folder, but inside the source tree, which sometimes bugs out CMake download project checkout upgrade:

HEAD detached at 15bd593a
Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
	modified:   BuildTools/File2Include/bin/Linux/File2String

no changes added to commit (use "git add" and/or "git commit -a")

with the following git error during the checkout:

error: Your local changes to the following files would be overwritten by checkout:
	BuildTools/File2Include/bin/Linux/File2String
Please commit your changes or stash them before you switch branches.
Aborting

I think a good idea would be to move this binary file to the build output folder.

**Comment by TheMostDiligent** [comment]
There File2String executable has been removed and replaced with a python script - please try to get the latest version and test.

**Comment by speedym** [comment]
I think I know what happened - previous versions of Diligent modified File2String binary and then git refused to checkout the new version of Diligent which deletes it, as git refuses to delete locally modified files on git checkout / git pull.

This one can be closed, thanks for the fix.
