### ISSUE TITLE
DiligentTools generated files are not generated in the output binary folder

### ISSUE THREAD

**Issue by speedym** [DiligentGraphics/DiligentTools#99]
Similar to the File2String tool, generated files are stored in the source tree instead of the binary tree:

error: Your local changes to the following files would be overwritten by checkout:
	RenderStateNotationParser/generated/BlendStateParser.hpp
	RenderStateNotationParser/generated/CommonParser.hpp
	RenderStateNotationParser/generated/DepthStencilStateParser.hpp
	RenderStateNotationParser/generated/GraphicsTypesParser.hpp
	RenderStateNotationParser/generated/InputLayoutParser.hpp
	RenderStateNotationParser/generated/PipelineResourceSignatureParser.hpp
	RenderStateNotationParser/generated/PipelineStateParser.hpp
	RenderStateNotationParser/generated/RasterizerStateParser.hpp
	RenderStateNotationParser/generated/RenderPassParser.hpp
	RenderStateNotationParser/generated/SamplerParser.hpp
	RenderStateNotationParser/generated/SerializationDeviceParser.hpp
	RenderStateNotationParser/generated/ShaderParser.hpp
	RenderStateNotationParser/generated/ShaderResourceVariableParser.hpp
Please commit your changes or stash them before you switch branches.
Aborting
CMake Error at /xxxx/3rdparty/.cache/DiligentTools/DiligentTools-download-prefix/tmp/DiligentTools-download-gitupdate.cmake:201 (message):
  Failed to checkout tag: 'f32158c73955aac5db1b1a8cec821fedaf34555d'

This makes upgrading to latest Diligent problematic and requires manual steps.

**Comment by TheMostDiligent** [comment]
@MikhailGorobets Please fix this branch: https://github.com/DiligentGraphics/DiligentTools/tree/rsn_generated_files_fix
Parser file generation on Mac->Emscripten has always been broken. It worked before because the files were checked into source.
